### ISSUE TITLE
[common-core] redis cache

### ISSUE THREAD

**Issue by Alice52** [Alice52/practice#13]
1. should config redis as cache management

```java
    /**
     * Notice: if donnot config redis as CacheManager, it will use memory as CacheManager.
     *
     * @param factory
     * @return
     */
    @Bean
    public CacheManager cacheManager(RedisConnectionFactory factory) {

        RedisCacheConfiguration config =
                RedisCacheConfiguration.defaultCacheConfig()
                        .entryTtl(Duration.ZERO)
                        .serializeKeysWith(
                                RedisSerializationContext.SerializationPair.fromSerializer(
                                        stringRedisSerializer))
                        .serializeValuesWith(
                                RedisSerializationContext.SerializationPair.fromSerializer(j2jrs))
                        .disableCachingNullValues();

        return RedisCacheManager.builder(factory).cacheDefaults(config).build();
    }
```

2. yml config

```yml
spring:
  redis:
    host: ENC(7KovIsPRdqwCfirn4hqyvyImWNCj0p/ag5rLhqKqMjiZ9HcC54uBFalQrr9h00lq)
    password: ENC(JIczcGuavcI1nX9NbM0YcDyHiQ834QTPhqmczAw+Qr8Nm6wPeq5p5M076HzPSbFF)
    port: ENC(AcXQfYO9iFqD0RYGjek03cmHP3k9y7fl9HEy41cg/mr0xoT4ApjXUbtlpKNK8OCp)
    database: 13
    enable: true
    redisson: classpath:redisson-dev.yml
#  cache:
#    # fix error: Cannot find cache named 'xx' for Builder Or Config Redis as cache management
#    type: simple
```
