### ISSUE TITLE
[common-api] boot starter

### ISSUE THREAD

**Issue by Alice52** [Alice52/practice#2]
## requirement

1. this jar can be reference by any boot project
2. version:
    - swagger: `3.0.0`
    - spring boot: `2.3.0` and at least `2.2.2`

3. default global Unified exception handler
4. base exception: based on `Assert + Enum`
5. task

    - [x] integration swagger
    - [ ] swagger error response definition
    - [x] base exception
    - [x] exception handler
   
6. diagram

    ![image](https://user-images.githubusercontent.com/42330329/102159798-31327c80-3ebf-11eb-8c5d-9292e4ec858a.png)

7. expectation
    - swagger, common response and common utils  can be import alone, which is no business with `spring boo version`
    - swagger can be controlled by config: `swagger properties`
    - common response should be satisfied follow condition: `can enable or disable this feature`
        1. HTTP's status should be hold, such as `200, 401, 400, 500, 404`
        2. Common response struct
              ```json
            // version 1: failed api status can be 200 or 400 by configuring
            {
                "code": 200,
                "message": "success",
                "data": {
                    "name": "zack"
                }
            }

            {
                "code": 50002,
                "message": "User is not exist!",
                "data": null
            }

            {
                "code": 40001,
                "message": "Not Found!",
                "data": null
            }


            // version 2, outdate, and not implemnt
            {
                "name": "zack"
            }

            {
                "code": 50002,
                "message": "User is not exist!",
            }

            {
                "code": 40001,
                "message": "Not Found!",
            }
           ```

**Comment by Alice52** [comment]
https://github.com/Alice52/Alice52/issues/19

**Comment by Alice52** [comment]
## swagger properties

- prefix: `swagger3`
- [ ] 1. enable
- [ ] 1. enable
- [ ] 1. enable
- [ ] 1. enable

**Comment by Alice52** [comment]
> swagger error response definition

1. https://github.com/springfox/springfox/issues/3646
2. enable BeanValidation for doc detail

**Comment by Alice52** [comment]
## exception

- [ ] 1.remove Lombok
- [ ] 2. handle validation issue
- [ ] 3. multi env
- [ ] 4. do re-search about http status

**Comment by Alice52** [comment]
> do re-search about HTTP status

donot use this solution.

**Comment by Alice52** [comment]
## common swagger  config porperties

```yml
swagger3:
  enabled: true
  ping: true
  author: alice52
  email: zzhang_xz@163.com
  group-name: default
  application-name: swagger test
  version: 1.0
  application-description: api doc
  token-name: sa
```

## common response config properties

```yml
common:
  response:
    # this can disable handler, advice, request feature
    enabled: true
    handler:
      # this can disable handler feature
      enabled: true
    advice: # if advice is disabled, it means request-id feature is disable too.
      # this can disable advice feature
      enabled: true
      code-name: code
      message-name: message
      data-name: R
      failed-api-status: 9202
    request-id:
      # this can disable request feature
      enabled: true
      key: requ-id
```
